### ISSUE TITLE
Edge浏览器中，滚动栏的样式有些不太合适

### ISSUE THREAD

**Issue by fxzxmicah** [leon-kfd/Dashboard#102]
这是扩展的：
![image](https://github.com/leon-kfd/Dashboard/assets/48860358/e08cb52c-3b04-48e1-9986-187a5c4c3f2c)
这是Github的（Github应该使用的是默认样式？不太确定）：
![image](https://github.com/leon-kfd/Dashboard/assets/48860358/e6a0f2de-2d5f-48da-82cf-2138b59e8b82)

**Comment by leon-kfd** [comment]
去看了一下，应该是Edge样式改版后的问题。
可以尝试在全局CSS注入一下代码
```css
body { overflow-x: hidden; }
body::-webkit-scrollbar {  width: 14px !important; }
body::-webkit-scrollbar-track {  
  background-color: #fff !important;
}
body::-webkit-scrollbar-thumb {
  background: #8b8b8b !important;
  border: 3px solid #fff !important;
  border-radius: 7px !important;
}
```
上面一些宽度、颜色可以自己再微调

![image](https://github.com/leon-kfd/Dashboard/assets/30256102/19e19033-873e-4c5d-baf6-e8fabcbaccda)


这个只是尽量看上去看原生的滚动条一样，因为样式表设置过滚动条样式后，滚动条无法通过覆盖代码恢复默认，详情请看这个：https://superuser.com/questions/380629/is-there-a-way-to-disable-custom-webkit-scrollbars
