### ISSUE TITLE
搜索框能调水平的宽（长）度，但是垂直的高度调不了。

### ISSUE THREAD

**Issue by ToBEaNewbility** [leon-kfd/Dashboard#103]
在某次同步数据后，我所有端的搜索款只能固定垂直的高度，这在高dpi显示器上显得太细了。
我第一次用的时候好像还可以调，现在改组件尺寸不起作用。
![屏幕截图 2023-12-03 231431](https://github.com/leon-kfd/Dashboard/assets/104293833/132f0782-4dfa-4969-a055-45bb42f348fc)

**Comment by leon-kfd** [comment]
看了一下代码，之前搜索组件设计是使用了rem做响应式，单独更改尺寸是不会生效的。如果你想更改高度，可以尝试全局注入以下css，使用缩放进行调整。
```css
.material-search .search-wrapper-box {
  transform: scale(1.4);
}
```

![image](https://github.com/leon-kfd/Dashboard/assets/30256102/4f7c2ccd-6212-4ba9-8be9-b8bb07077c8b)
![scale](https://github.com/leon-kfd/Dashboard/assets/30256102/3723de64-3b71-4142-8b68-5c62b5ddc53a)
