### ISSUE TITLE
希望每个书签支持自动居中。要不每次都得去手动调书签块的fx然后放在中间

### ISSUE THREAD

**Issue by foyue5666** [leon-kfd/Dashboard#79]

**Comment by leon-kfd** [comment]
去提供截图看看，应该可以使用注入CSS解决

**Comment by foyue5666** [comment]
对于我这种小白来讲……从零开始认识css好像不大现实
还是希望未来能支持gui直接修改吧😁
或者大佬贴个样式也行，我就直接抄作业了（滑稽）

**Comment by leon-kfd** [comment]
书签模块内部自动居中的CSS
```css
.bookmark-draggable-wrapper {
  justify-content: center !important;
}
.bookmark-draggable-wrapper .fake {
  display: none !important;
}
```
