### ISSUE TITLE
希望支持修改底色，就是当壁纸没加载出来的时候显示的那个暗紫色

### ISSUE THREAD

**Issue by foyue5666** [leon-kfd/Dashboard#80]

**Comment by leon-kfd** [comment]
可尝试使用注入全局CSS的方法。
在全局设置找到注入CSS的地方写入
```css
.page > .wrapper { background: #6044d1 !important; }
```
